# Generated by Django 3.1.3 on 2020-11-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201015_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='images/male_doc.png', upload_to='images/'),
        ),
    ]
