# Generated by Django 3.1.3 on 2020-11-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='media/images/male_doc.png', upload_to='images/'),
        ),
    ]
