# Generated by Django 3.1.3 on 2020-11-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201105_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='images/male_doc.png', upload_to='images/'),
        ),
    ]
