# Generated by Django 3.1.3 on 2020-12-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201105_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Anesthetics', 'ANES'), ('Cardiologist', 'CRDLGY'), ('Dermatologists', 'DMRTLGY'), ('Radiology', 'RAD'), ('Gynecology', 'GYN')], default='GYN', max_length=50),
        ),
    ]
