# Generated by Django 3.1.2 on 2020-11-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('One', 1), ('Two', 2), ('Three', 3), ('Four', 4)], default='One', max_length=100)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
